# # Use an immediate variable to evaluate `MAKEFILE_LIST` now
# USEMODULE_INCLUDES_display_handler += $(LAST_MAKEFILEDIR)/include
# #USEMODULE_INCLUDES_external_module += $(LAST_MAKEFILEDIR)/image
# USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_display_handler)


INCLUDES += -I$(LAST_MAKEFILEDIR)/include
INCLUDES += -I$(LAST_MAKEFILEDIR)/image
