BOARD ?= feather-nrf52840-sense
UPLINK ?= cdc-ecm
# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

include $(RIOTBASE)/examples/gnrc_border_router/Makefile