#!/bin/bash
set -e

# Create keycloak user and database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_BACKEND_USER} WITH PASSWORD '${POSTGRES_BACKEND_PASSWORD}';
	CREATE DATABASE ${POSTGRES_BACKEND_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_BACKEND_DB} TO ${POSTGRES_BACKEND_USER};
EOSQL

# Be sure the schema exists
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  \connect ${POSTGRES_BACKEND_DB};
  CREATE SCHEMA IF NOT EXISTS ${POSTGRES_BACKEND_DB} AUTHORIZATION ${POSTGRES_BACKEND_USER};
EOSQL
