#pragma once

#include <cstdint>

extern "C" enum EVENTS: uint16_t {
    TERMINATE,
    WILDCARD, // Subscribe to all events [Special case]
    PING,
    PONG,
    BUTTON_UP_PRESSED,
    BUTTON_UP_RELEASED,
    BUTTON_LEFT_PRESSED,
    BUTTON_LEFT_RELEASED,
    BUTTON_DOWN_PRESSED,
    BUTTON_DOWN_RELEASED,
    BUTTON_RIGHT_PRESSED,
    BUTTON_RIGHT_RELEASED,
    BUTTON_EXTRA_PRESSED,
    BUTTON_EXTRA_RELEASED,
};
