#pragma once

#include <cstdint>

extern "C" enum EVENTS: uint16_t {
    TERMINATE,
    WILDCARD, // Subscribe to all events [Special case]
    PING,
    PONG,
    BUTTON_OK_PRESSED,
    BUTTON_OK_RELEASED,
    BUTTON_UP_PRESSED,
    BUTTON_UP_RELEASED,
    BUTTON_LEFT_PRESSED,
    BUTTON_LEFT_RELEASED,
    BUTTON_DOWN_PRESSED,
    BUTTON_DOWN_RELEASED,
    BUTTON_RIGHT_PRESSED,
    BUTTON_RIGHT_RELEASED,
    PET_FEED,
    PET_PLAY,
    PET_WASH,
    PET_MEDICATE,
    PET_HUNGRY,
    PET_ILL,
    PET_BORED,
    PET_DIRTY,
    PET_FEED,
    PET_MEDICATE,
    PET_PLAY,
    PET_CLEAN,
};
