USEPKG += wakaama
# Include packages that pull up and auto-init the link layer.
# NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
# Specify the mandatory networking modules
USEMODULE += gnrc_ipv6_router_default
# Additional networking modules that can be dropped if not needed
USEMODULE += gnrc_icmpv6_echo
# Add also the shell, some shell commands
USEMODULE += shell
USEMODULE += shell_cmds_default
USEMODULE += ps
# USEMODULE += wakaama_client_dtls
# # Specify sock DTLS implementation
# USEPKG += tinydtls
# # tinydtls needs crypto secure PRNG
# USEMODULE += prng_sha1prng
