include $(RIOTBASE)/Makefile.base

#Wakamaa logs
#CFLAGS += -DCONFIG_LWM2M_WITH_LOGS=1

#SERVER_URI = '"coap://[2001:db8:1::1]"'


# add DTLS support
#USEMODULE += wakaama_client_dtls

# Specify sock DTLS implementation
#USEPKG += tinydtls
# tinydtls needs crypto secure PRNG
#USEMODULE += prng_sha1prng
